services:
  - type: web
    name: starksuite
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
